In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


green_prices_raw = pd.read_csv('green coffee prices.csv')
production_raw = pd.read_csv('Coffee_production.csv')
coffee_export_raw = pd.read_csv('Coffee_export.csv')
coffee_import_raw = pd.read_csv('Coffee_import.csv')
consumption_importers_raw = pd.read_csv('Coffee_importers_consumption.csv')
consumption_domestic_raw = pd.read_csv('Coffee_domestic_consumption.csv')

# work copies
green_prices = green_prices_raw.copy()
production = production_raw.copy()
coffee_export = coffee_export_raw.copy()
coffee_import = coffee_import_raw.copy()
consumption_importers = consumption_importers_raw.copy()
consumption_domestic = consumption_domestic_raw.copy()

display(green_prices.head(2))
display(production.head(2))
display(coffee_export.head(2))    
display(coffee_import.head(2))
display(consumption_importers.head(2))
display(consumption_domestic.head(2))

         Date   Value
0  06/02/1969  0.3725
1  06/03/1969  0.3725

,Country,Coffee type,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_production
0,Angola,Robusta/Arabica,3000000.0,4740000.0,4680000.0,1980000.0,4620000.0,3720000.0,4260000.0,3840000.0,...,1740000.0,1980000.0,2100000.0,2340000.0,2460000.0,2700000.0,2100000.0,2520000.0,3120000.0,82080000.0
1,Bolivia (Plurinational State of),Arabica,7380000.0,6240000.0,7200000.0,3060000.0,7020000.0,8520000.0,7500000.0,8460000.0,...,7920000.0,6300000.0,7200000.0,6000000.0,5040000.0,4680000.0,5040000.0,4980000.0,4860000.0,207000000.0

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_export
0,Angola,5040000,4260000,4800000,2340000,480000,2460000,3120000,3000000,3240000,...,480000,480000,360000,540000,660000,660000,540000,540000,1380000,43320000
1,Bolivia (Plurinational State of),9360000,4440000,5760000,2820000,5040000,5640000,7380000,6660000,5820000,...,4440000,3780000,3300000,3720000,1800000,1320000,1560000,1320000,1200000,137460000

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_import
0,Austria,112800000,123480000,132360000,110160000,85020000,73860000,72600000,77640000,77580000,...,87120000,93540000,93300000,91500000,90780000,89700000,87600000,85740000,86880000,2765760000
1,Belgium,0,0,0,0,0,0,0,0,0,...,349680000,340080000,330120000,312720000,332040000,363120000,340620000,344520000,371940000,6240540000

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_import_consumption
0,Austria,80400000,78120000,72720000,80100000,65160000,60720000,64560000,65220000,66300000,...,67020000,76140000,74940000,68100000,68160000,71580000,69720000,70320000,70380000,1904520000
1,Belgium,0,0,0,0,0,0,0,0,0,...,56040000,54900000,74700000,75540000,64440000,90120000,78000000,81900000,71100000,1460520000

,Country,Coffee type,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_domestic_consumption
0,Angola,Robusta/Arabica,1200000,1800000,2100000,1200000,1500000,600000,1200000,2400000,...,1800000,1800000,1800000,1800000,1800000,1800000,1800000,1800000,1800000,46500000
1,Bolivia (Plurinational State of),Arabica,1500000,1620000,1650000,1710000,1770000,1830000,1890000,1950000,...,2940000,3030000,3120000,3210000,3300000,3420000,3510000,3600000,3660000,75180000

In [5]:
# quick profile check for each dataframe

dfs = {
    "green_prices": green_prices,
    "production": production,
    "coffee_export": coffee_export,
    "coffee_import": coffee_import,
    "consumption_importers": consumption_importers,
    "consumption_domestic": consumption_domestic,
}

for name, df in dfs.items():
    print("\n" + "="*80)
    print(name, df.shape)
    print(df.info())
    print("Missing:\n", df.isna().sum().sort_values(ascending=False).head(15))
    print("Duplicates:", df.duplicated().sum())

================================================================================
green_prices (14362, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14362 entries, 0 to 14361
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    14362 non-null  object
 1   Value   14362 non-null  float64
dtypes: float64(1), object(1)
memory usage: 224.5+ KB
None
Missing:
 Date     0
Value    0
dtype: int64
Duplicates: 0

================================================================================
production (55, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           55 non-null     object
 1   Coffee type       55 non-null     object
 2   1990/91           55 non-null     float64
 3   1991/92           55 non-null     float64
 4   1992/93           55 non-null     float64
 5   1993/94           55 non-null     float64
 6   1994/95           55 non-null     float64
 7   1995/96           55 non-null     float64
 8   1996/97           55 non-null     float64
 9   1997/98           55 non-null     float64
 10  1998/99           55 non-null     float64
 11  1999/00           55 non-null     float64
 12  2000/01           55 non-null     float64
 13  2001/02           55 non-null     float64
 14  2002/03           55 non-null     float64
 15  2003/04           55 non-null     float64
 16  2004/05           55 non-null     float64
 17  2005/06           55 non-null     float64
 18  2006/07           55 non-null     float64
 19  2007/08           55 non-null     float64
 20  2008/09           55 non-null     float64
 21  2009/10           55 non-null     float64
 22  2010/11           55 non-null     float64
 23  2011/12           55 non-null     float64
 24  2012/13           55 non-null     float64
 25  2013/14           55 non-null     float64
 26  2014/15           55 non-null     float64
 27  2015/16           55 non-null     float64
 28  2016/17           55 non-null     float64
 29  2017/18           55 non-null     float64
 30  2018/19           55 non-null     float64
 31  2019/20           55 non-null     float64
 32  Total_production  55 non-null     float64
dtypes: float64(31), object(2)
memory usage: 14.3+ KB
None
Missing:
 Country        0
Coffee type    0
1990/91        0
1991/92        0
1992/93        0
1993/94        0
1994/95        0
1995/96        0
1996/97        0
1997/98        0
1998/99        0
1999/00        0
2000/01        0
2001/02        0
2002/03        0
dtype: int64
Duplicates: 0

================================================================================
coffee_export (55, 32)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       55 non-null     object
 1   1990          55 non-null     int64
 2   1991          55 non-null     int64
 3   1992          55 non-null     int64
 4   1993          55 non-null     int64
 5   1994          55 non-null     int64
 6   1995          55 non-null     int64
 7   1996          55 non-null     int64
 8   1997          55 non-null     int64
 9   1998          55 non-null     int64
 10  1999          55 non-null     int64
 11  2000          55 non-null     int64
 12  2001          55 non-null     int64
 13  2002          55 non-null     int64
 14  2003          55 non-null     int64
 15  2004          55 non-null     int64
 16  2005          55 non-null     int64
 17  2006          55 non-null     int64
 18  2007          55 non-null     int64
 19  2008          55 non-null     int64
 20  2009          55 non-null     int64
 21  2010          55 non-null     int64
 22  2011          55 non-null     int64
 23  2012          55 non-null     int64
 24  2013          55 non-null     int64
 25  2014          55 non-null     int64
 26  2015          55 non-null     int64
 27  2016          55 non-null     int64
 28  2017          55 non-null     int64
 29  2018          55 non-null     int64
 30  2019          55 non-null     int64
 31  Total_export  55 non-null     int64
dtypes: int64(31), object(1)
memory usage: 13.9+ KB
None
Missing:
 Country    0
1990       0
1991       0
1992       0
1993       0
1994       0
1995       0
1996       0
1997       0
1998       0
1999       0
2000       0
2001       0
2002       0
2003       0
dtype: int64
Duplicates: 0

================================================================================
coffee_import (35, 32)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       35 non-null     object
 1   1990          35 non-null     int64
 2   1991          35 non-null     int64
 3   1992          35 non-null     int64
 4   1993          35 non-null     int64
 5   1994          35 non-null     int64
 6   1995          35 non-null     int64
 7   1996          35 non-null     int64
 8   1997          35 non-null     int64
 9   1998          35 non-null     int64
 10  1999          35 non-null     int64
 11  2000          35 non-null     int64
 12  2001          35 non-null     int64
 13  2002          35 non-null     int64
 14  2003          35 non-null     int64
 15  2004          35 non-null     int64
 16  2005          35 non-null     int64
 17  2006          35 non-null     int64
 18  2007          35 non-null     int64
 19  2008          35 non-null     int64
 20  2009          35 non-null     int64
 21  2010          35 non-null     int64
 22  2011          35 non-null     int64
 23  2012          35 non-null     int64
 24  2013          35 non-null     int64
 25  2014          35 non-null     int64
 26  2015          35 non-null     int64
 27  2016          35 non-null     int64
 28  2017          35 non-null     int64
 29  2018          35 non-null     int64
 30  2019          35 non-null     int64
 31  Total_import  35 non-null     int64
dtypes: int64(31), object(1)
memory usage: 8.9+ KB
None
Missing:
 Country    0
1990       0
1991       0
1992       0
1993       0
1994       0
1995       0
1996       0
1997       0
1998       0
1999       0
2000       0
2001       0
2002       0
2003       0
dtype: int64
Duplicates: 0

================================================================================
consumption_importers (35, 32)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Country                   35 non-null     object
 1   1990                      35 non-null     int64
 2   1991                      35 non-null     int64
 3   1992                      35 non-null     int64
 4   1993                      35 non-null     int64
 5   1994                      35 non-null     int64
 6   1995                      35 non-null     int64
 7   1996                      35 non-null     int64
 8   1997                      35 non-null     int64
 9   1998                      35 non-null     int64
 10  1999                      35 non-null     int64
 11  2000                      35 non-null     int64
 12  2001                      35 non-null     int64
 13  2002                      35 non-null     int64
 14  2003                      35 non-null     int64
 15  2004                      35 non-null     int64
 16  2005                      35 non-null     int64
 17  2006                      35 non-null     int64
 18  2007                      35 non-null     int64
 19  2008                      35 non-null     int64
 20  2009                      35 non-null     int64
 21  2010                      35 non-null     int64
 22  2011                      35 non-null     int64
 23  2012                      35 non-null     int64
 24  2013                      35 non-null     int64
 25  2014                      35 non-null     int64
 26  2015                      35 non-null     int64
 27  2016                      35 non-null     int64
 28  2017                      35 non-null     int64
 29  2018                      35 non-null     int64
 30  2019                      35 non-null     int64
 31  Total_import_consumption  35 non-null     int64
dtypes: int64(31), object(1)
memory usage: 8.9+ KB
None
Missing:
 Country    0
1990       0
1991       0
1992       0
1993       0
1994       0
1995       0
1996       0
1997       0
1998       0
1999       0
2000       0
2001       0
2002       0
2003       0
dtype: int64
Duplicates: 0

================================================================================
consumption_domestic (55, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Country                     55 non-null     object
 1   Coffee type                 55 non-null     object
 2   1990/91                     55 non-null     int64
 3   1991/92                     55 non-null     int64
 4   1992/93                     55 non-null     int64
 5   1993/94                     55 non-null     int64
 6   1994/95                     55 non-null     int64
 7   1995/96                     55 non-null     int64
 8   1996/97                     55 non-null     int64
 9   1997/98                     55 non-null     int64
 10  1998/99                     55 non-null     int64
 11  1999/00                     55 non-null     int64
 12  2000/01                     55 non-null     int64
 13  2001/02                     55 non-null     int64
 14  2002/03                     55 non-null     int64
 15  2003/04                     55 non-null     int64
 16  2004/05                     55 non-null     int64
 17  2005/06                     55 non-null     int64
 18  2006/07                     55 non-null     int64
 19  2007/08                     55 non-null     int64
 20  2008/09                     55 non-null     int64
 21  2009/10                     55 non-null     int64
 22  2010/11                     55 non-null     int64
 23  2011/12                     55 non-null     int64
 24  2012/13                     55 non-null     int64
 25  2013/14                     55 non-null     int64
 26  2014/15                     55 non-null     int64
 27  2015/16                     55 non-null     int64
 28  2016/17                     55 non-null     int64
 29  2017/18                     55 non-null     int64
 30  2018/19                     55 non-null     int64
 31  2019/20                     55 non-null     int64
 32  Total_domestic_consumption  55 non-null     int64
dtypes: int64(31), object(2)
memory usage: 14.3+ KB
None
Missing:
 Country        0
Coffee type    0
1990/91        0
1991/92        0
1992/93        0
1993/94        0
1994/95        0
1995/96        0
1996/97        0
1997/98        0
1998/99        0
1999/00        0
2000/01        0
2001/02        0
2002/03        0
dtype: int64
Duplicates: 0

In [6]:
# standardize column names
# strips whitespace, converts to lowercase, replaces dots and non-alphanumeric characters with underscores, and removes leading/trailing underscores
for df in [
    green_prices,
    production,
    coffee_export,
    coffee_import,
    consumption_importers,
    consumption_domestic,
]:
    df.columns = (
        df.columns
          .str.strip()
          .str.lower()
          .str.replace(".", "_", regex=False)
          .str.replace(r"[^\w]+", "_", regex=True)
          .str.replace(r"^(\d{4})_\d{2}$", r"\1", regex=True)
          .str.strip("_")
    )

# check all dataframes again after column name standardization
for name, df in dfs.items():
    print("\n" + "="*80)
    print(name, df.shape)
    print(df.columns)

================================================================================
green_prices (14362, 2)
Index(['date', 'value'], dtype='object')

================================================================================
production (55, 33)
Index(['country', 'coffee_type', '1990', '1991', '1992', '1993', '1994',
       '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       'total_production'],
      dtype='object')

================================================================================
coffee_export (55, 32)
Index(['country', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', 'total_export'],
      dtype='object')

================================================================================
coffee_import (35, 32)
Index(['country', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', 'total_import'],
      dtype='object')

================================================================================
consumption_importers (35, 32)
Index(['country', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', 'total_import_consumption'],
      dtype='object')

================================================================================
consumption_domestic (55, 33)
Index(['country', 'coffee_type', '1990', '1991', '1992', '1993', '1994',
       '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       'total_domestic_consumption'],
      dtype='object')

In [7]:
# remove only the last columns before pivoting
production = production.iloc[:, :-1]
coffee_export = coffee_export.iloc[:, :-1]
coffee_import = coffee_import.iloc[:, :-1]
consumption_importers = consumption_importers.iloc[:, :-1]
consumption_domestic = consumption_domestic.iloc[:, :-1]


# check column names again after removing total rows to make sure we don't have any duplicates or issues before pivoting
print("Production columns:", production.columns.tolist())
print("Export columns:", coffee_export.columns.tolist())
print("Import columns:", coffee_import.columns.tolist())
print("Consumption Importers columns:", consumption_importers.columns.tolist())
print("Consumption Domestic columns:", consumption_domestic.columns.tolist())

Production columns: ['country', 'coffee_type', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']
Export columns: ['country', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']
Import columns: ['country', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']
Consumption Importers columns: ['country', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']
Consumption Domestic columns: ['country', 'coffee_type', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']

In [8]:
# pivot the production, export, import, and consumption dataframes to have years as rows and countries as columns
# ensure columns are country, coffee_type (only in production), year, amount for easier analysis and merging later on
production_pivot = production.melt(id_vars=["country", "coffee_type"], var_name="year", value_name="production")
export_pivot = coffee_export.melt(id_vars=["country"], var_name="year", value_name="export")
import_pivot = coffee_import.melt(id_vars=["country"], var_name="year", value_name="import")
consumption_importers_pivot = consumption_importers.melt(id_vars=["country"], var_name="year", value_name="consumption_importers")
consumption_domestic_pivot = consumption_domestic.melt(id_vars=["country","coffee_type"], var_name="year", value_name="consumption_domestic")

# convert year to numeric as integer, coercing errors to NaN (e.g. if there are any non-year values in the year column)
for df in [
    production_pivot,
    export_pivot,
    import_pivot,
    consumption_importers_pivot,
    consumption_domestic_pivot,
]:
    df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")

# check the pivoted dataframes
display(production_pivot.head(2))
display(export_pivot.head(2))
display(import_pivot.head(2))
display(consumption_importers_pivot.head(2))
display(consumption_domestic_pivot.head(2))

                            country      coffee_type  year  production
0                            Angola  Robusta/Arabica  1990   3000000.0
1  Bolivia (Plurinational State of)          Arabica  1990   7380000.0

                            country  year   export
0                            Angola  1990  5040000
1  Bolivia (Plurinational State of)  1990  9360000

      country  year     import
0     Austria  1990  112800000
1     Belgium  1990          0

      country  year  consumption_importers
0     Austria  1990               80400000
1     Belgium  1990                      0

,country,coffee_type,year,consumption_domestic
0,Angola,Robusta/Arabica,1990,1200000
1,Bolivia (Plurinational State of),Arabica,1990,1500000

In [9]:
production_pivot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1650 entries, 0 to 1649
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      1650 non-null   object
 1   coffee_type  1650 non-null   object
 2   year         1650 non-null   Int64
 3   production   1650 non-null   float64
dtypes: Int64(1), float64(1), object(2)
memory usage: 53.3+ KB

In [10]:
# standardize country names in all dataframes to ensure consistency for merging and analysis
# this is a simple standardization that can be expanded with a mapping dictionary for known variations (e.g. "United States" vs "USA")
for df in [
    production_pivot,
    export_pivot,
    import_pivot,
    consumption_importers_pivot,
    consumption_domestic_pivot,
]:
    df["country"] = (
        df["country"]
          .str.strip()
          .str.title()
          .str.replace(r"\s+", " ", regex=True)  # replace multiple spaces with single space
          .str.replace(r"[^\w\s]", "", regex=True)  # remove punctuation
    )

#check the pivot dataframes again after country name standardization
for df in [
    production_pivot,
    export_pivot,
    import_pivot,
    consumption_importers_pivot,
    consumption_domestic_pivot,
]:
    print(df["country"].value_counts())

country
Angola                             30
Bolivia Plurinational State Of     30
Brazil                             30
Burundi                            30
Ecuador                            30
Indonesia                          30
Madagascar                         30
Malawi                             30
Papua New Guinea                   30
Paraguay                           30
Peru                               30
Rwanda                             30
TimorLeste                         30
Zimbabwe                           30
Congo                              30
Cuba                               30
Dominican Republic                 30
Haiti                              30
Philippines                        30
Tanzania                           30
Zambia                             30
Cameroon                           30
Central African Republic           30
Colombia                           30
Costa Rica                         30
Côte DIvoire                       30
Democratic Republic Of Congo       30
El Salvador                        30
Equatorial Guinea                  30
Ethiopia                           30
Gabon                              30
Ghana                              30
Guatemala                          30
Guinea                             30
Guyana                             30
Honduras                           30
India                              30
Jamaica                            30
Kenya                              30
Lao PeopleS Democratic Republic    30
Liberia                            30
Mexico                             30
Nepal                              30
Nicaragua                          30
Nigeria                            30
Panama                             30
Sierra Leone                       30
Sri Lanka                          30
Thailand                           30
Togo                               30
Trinidad  Tobago                   30
Uganda                             30
Venezuela                          30
Viet Nam                           30
Yemen                              30
Name: count, dtype: int64
country
Angola                             30
Bolivia Plurinational State Of     30
Brazil                             30
Burundi                            30
Cameroon                           30
Central African Republic           30
Colombia                           30
Congo                              30
Costa Rica                         30
Côte DIvoire                       30
Cuba                               30
Democratic Republic Of Congo       30
Dominican Republic                 30
Ecuador                            30
El Salvador                        30
Equatorial Guinea                  30
Ethiopia                           30
Gabon                              30
Ghana                              30
Guatemala                          30
Guinea                             30
Guyana                             30
Haiti                              30
Honduras                           30
India                              30
Indonesia                          30
Jamaica                            30
Kenya                              30
Lao PeopleS Democratic Republic    30
Liberia                            30
Madagascar                         30
Malawi                             30
Mexico                             30
Nepal                              30
Nicaragua                          30
Nigeria                            30
Panama                             30
Papua New Guinea                   30
Paraguay                           30
Peru                               30
Philippines                        30
Rwanda                             30
Sierra Leone                       30
Sri Lanka                          30
Tanzania                           30
Thailand                           30
TimorLeste                         30
Togo                               30
Trinidad  Tobago                   30
Uganda                             30
Venezuela                          30
Viet Nam                           30
Yemen                              30
Zambia                             30
Zimbabwe                           30
Name: count, dtype: int64
country
Austria                     30
Belgium                     30
BelgiumLuxembourg           30
Bulgaria                    30
Croatia                     30
Cyprus                      30
Czechia                     30
Denmark                     30
Estonia                     30
Finland                     30
France                      30
Germany                     30
Greece                      30
Hungary                     30
Ireland                     30
Italy                       30
Latvia                      30
Lithuania                   30
Luxembourg                  30
Malta                       30
Netherlands                 30
Poland                      30
Portugal                    30
Romania                     30
Slovakia                    30
Slovenia                    30
Spain                       30
Sweden                      30
Japan                       30
Norway                      30
Russian Federation          30
Switzerland                 30
Tunisia                     30
United Kingdom              30
United States Of America    30
Name: count, dtype: int64
country
Austria                     30
Belgium                     30
BelgiumLuxembourg           30
Bulgaria                    30
Croatia                     30
Cyprus                      30
Czechia                     30
Denmark                     30
Estonia                     30
Finland                     30
France                      30
Germany                     30
Greece                      30
Hungary                     30
Ireland                     30
Italy                       30
Latvia                      30
Lithuania                   30
Luxembourg                  30
Malta                       30
Netherlands                 30
Poland                      30
Portugal                    30
Romania                     30
Slovakia                    30
Slovenia                    30
Spain                       30
Sweden                      30
Japan                       30
Norway                      30
Russian Federation          30
Switzerland                 30
Tunisia                     30
United Kingdom              30
United States Of America    30
Name: count, dtype: int64
country
Angola                             30
Bolivia Plurinational State Of     30
Brazil                             30
Burundi                            30
Ecuador                            30
Indonesia                          30
Madagascar                         30
Malawi                             30
Papua New Guinea                   30
Paraguay                           30
Peru                               30
Rwanda                             30
TimorLeste                         30
Zimbabwe                           30
Congo                              30
Cuba                               30
Dominican Republic                 30
Haiti                              30
Philippines                        30
Tanzania                           30
Zambia                             30
Cameroon                           30
Central African Republic           30
Colombia                           30
Costa Rica                         30
Côte DIvoire                       30
Democratic Republic Of Congo       30
El Salvador                        30
Equatorial Guinea                  30
Ethiopia                           30
Gabon                              30
Ghana                              30
Guatemala                          30
Guinea                             30
Guyana                             30
Honduras                           30
India                              30
Jamaica                            30
Kenya                              30
Lao PeopleS Democratic Republic    30
Liberia                            30
Mexico                             30
Nepal                              30
Nicaragua                          30
Nigeria                            30
Panama                             30
Sierra Leone                       30
Sri Lanka                          30
Thailand                           30
Togo                               30
Trinidad  Tobago                   30
Uganda                             30
Venezuela                          30
Viet Nam                           30
Yemen                              30
Name: count, dtype: int64

In [11]:
# correct country names based on the unique values observed in the previous step, using a mapping dictionary to replace known variations with a standardized name
country_map = {
    "Bolivia Plurinational State Of": "Bolivia",
    "Timorleste": "Timor-Leste",
    "Côte Divoire": "Côte d’Ivoire",
    "Democratic Republic Of Congo": "Democratic Republic of the Congo",
    "Congo": "Republic of the Congo",
    "Lao Peoples Democratic Republic": "Lao People’s Democratic Republic",
    "Trinidad Tobago": "Trinidad and Tobago",
    "Belgiumluxembourg": "Belgium-Luxembourg"
    }

for df in [
    production_pivot,
    export_pivot,
    import_pivot,
    consumption_importers_pivot,
    consumption_domestic_pivot,
]:
    df["country"] = df["country"].astype(str).str.strip().replace(country_map)

In [ ]:
# quick country name check
for df in [
    production_pivot,
    export_pivot,
    import_pivot,
    consumption_importers_pivot,
    consumption_domestic_pivot,
]:
    print(df["country"].unique())

['Angola' 'Bolivia' 'Brazil' 'Burundi' 'Ecuador' 'Indonesia' 'Madagascar'
 'Malawi' 'Papua New Guinea' 'Paraguay' 'Peru' 'Rwanda' 'TimorLeste'
 'Zimbabwe' 'Republic of the Congo' 'Cuba' 'Dominican Republic' 'Haiti'
 'Philippines' 'Tanzania' 'Zambia' 'Cameroon' 'Central African Republic'
 'Colombia' 'Costa Rica' 'Côte DIvoire' 'Democratic Republic of the Congo'
 'El Salvador' 'Equatorial Guinea' 'Ethiopia' 'Gabon' 'Ghana' 'Guatemala'
 'Guinea' 'Guyana' 'Honduras' 'India' 'Jamaica' 'Kenya'
 'Lao PeopleS Democratic Republic' 'Liberia' 'Mexico' 'Nepal' 'Nicaragua'
 'Nigeria' 'Panama' 'Sierra Leone' 'Sri Lanka' 'Thailand' 'Togo'
 'Trinidad  Tobago' 'Uganda' 'Venezuela' 'Viet Nam' 'Yemen']
['Angola' 'Bolivia' 'Brazil' 'Burundi' 'Cameroon'
 'Central African Republic' 'Colombia' 'Republic of the Congo'
 'Costa Rica' 'Côte DIvoire' 'Cuba' 'Democratic Republic of the Congo'
 'Dominican Republic' 'Ecuador' 'El Salvador' 'Equatorial Guinea'
 'Ethiopia' 'Gabon' 'Ghana' 'Guatemala' 'Guinea' 'Guyana' 'Haiti'
 'Honduras' 'India' 'Indonesia' 'Jamaica' 'Kenya'
 'Lao PeopleS Democratic Republic' 'Liberia' 'Madagascar' 'Malawi'
 'Mexico' 'Nepal' 'Nicaragua' 'Nigeria' 'Panama' 'Papua New Guinea'
 'Paraguay' 'Peru' 'Philippines' 'Rwanda' 'Sierra Leone' 'Sri Lanka'
 'Tanzania' 'Thailand' 'TimorLeste' 'Togo' 'Trinidad  Tobago' 'Uganda'
 'Venezuela' 'Viet Nam' 'Yemen' 'Zambia' 'Zimbabwe']
['Austria' 'Belgium' 'BelgiumLuxembourg' 'Bulgaria' 'Croatia' 'Cyprus'
 'Czechia' 'Denmark' 'Estonia' 'Finland' 'France' 'Germany' 'Greece'
 'Hungary' 'Ireland' 'Italy' 'Latvia' 'Lithuania' 'Luxembourg' 'Malta'
 'Netherlands' 'Poland' 'Portugal' 'Romania' 'Slovakia' 'Slovenia' 'Spain'
 'Sweden' 'Japan' 'Norway' 'Russian Federation' 'Switzerland' 'Tunisia'
 'United Kingdom' 'United States Of America']
['Austria' 'Belgium' 'BelgiumLuxembourg' 'Bulgaria' 'Croatia' 'Cyprus'
 'Czechia' 'Denmark' 'Estonia' 'Finland' 'France' 'Germany' 'Greece'
 'Hungary' 'Ireland' 'Italy' 'Latvia' 'Lithuania' 'Luxembourg' 'Malta'
 'Netherlands' 'Poland' 'Portugal' 'Romania' 'Slovakia' 'Slovenia' 'Spain'
 'Sweden' 'Japan' 'Norway' 'Russian Federation' 'Switzerland' 'Tunisia'
 'United Kingdom' 'United States Of America']
['Angola' 'Bolivia' 'Brazil' 'Burundi' 'Ecuador' 'Indonesia' 'Madagascar'
 'Malawi' 'Papua New Guinea' 'Paraguay' 'Peru' 'Rwanda' 'TimorLeste'
 'Zimbabwe' 'Republic of the Congo' 'Cuba' 'Dominican Republic' 'Haiti'
 'Philippines' 'Tanzania' 'Zambia' 'Cameroon' 'Central African Republic'
 'Colombia' 'Costa Rica' 'Côte DIvoire' 'Democratic Republic of the Congo'
 'El Salvador' 'Equatorial Guinea' 'Ethiopia' 'Gabon' 'Ghana' 'Guatemala'
 'Guinea' 'Guyana' 'Honduras' 'India' 'Jamaica' 'Kenya'
 'Lao PeopleS Democratic Republic' 'Liberia' 'Mexico' 'Nepal' 'Nicaragua'
 'Nigeria' 'Panama' 'Sierra Leone' 'Sri Lanka' 'Thailand' 'Togo'
 'Trinidad  Tobago' 'Uganda' 'Venezuela' 'Viet Nam' 'Yemen']

In [13]:
# check types and formats of all columns in the pivoted dataframes to ensure they are correct for analysis (e.g. numeric columns should be numeric, year should be integer, etc.)
for df in [
    green_prices,
    production_pivot,
    export_pivot,
    import_pivot,
    consumption_importers_pivot,
    consumption_domestic_pivot,
]:
    print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14362 entries, 0 to 14361
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    14362 non-null  object
 1   value   14362 non-null  float64
dtypes: float64(1), object(1)
memory usage: 224.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1650 entries, 0 to 1649
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      1650 non-null   object
 1   coffee_type  1650 non-null   object
 2   year         1650 non-null   Int64
 3   production   1650 non-null   float64
dtypes: Int64(1), float64(1), object(2)
memory usage: 53.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1650 entries, 0 to 1649
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  1650 non-null   object
 1   year     1650 non-null   Int64
 2   export   1650 non-null   int64
dtypes: Int64(1), int64(1), object(1)
memory usage: 40.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  1050 non-null   object
 1   year     1050 non-null   Int64
 2   import   1050 non-null   int64
dtypes: Int64(1), int64(1), object(1)
memory usage: 25.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   country                1050 non-null   object
 1   year                   1050 non-null   Int64
 2   consumption_importers  1050 non-null   int64
dtypes: Int64(1), int64(1), object(1)
memory usage: 25.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1650 entries, 0 to 1649
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   country               1650 non-null   object
 1   coffee_type           1650 non-null   object
 2   year                  1650 non-null   Int64
 3   consumption_domestic  1650 non-null   int64
dtypes: Int64(1), int64(1), object(2)
memory usage: 53.3+ KB
None

In [14]:
# change type for: 
# date in green_prices to datetime, 
# production to int,
# consumption_domestic to int

green_prices["date"] = pd.to_datetime(green_prices["date"], errors="coerce")
production_pivot["production"] = pd.to_numeric(production_pivot["production"], errors="coerce").astype("Int64")
consumption_domestic_pivot["consumption_domestic"] = pd.to_numeric(consumption_domestic_pivot["consumption_domestic"], errors="coerce").astype("Int64")

#recheck types after conversion
for df in [
    green_prices,
    production_pivot,
    export_pivot,
    import_pivot,
    consumption_importers_pivot,
    consumption_domestic_pivot,
]:
    print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14362 entries, 0 to 14361
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    14362 non-null  datetime64[ns]
 1   value   14362 non-null  float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 224.5 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1650 entries, 0 to 1649
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      1650 non-null   object
 1   coffee_type  1650 non-null   object
 2   year         1650 non-null   Int64
 3   production   1650 non-null   Int64
dtypes: Int64(2), object(2)
memory usage: 54.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1650 entries, 0 to 1649
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  1650 non-null   object
 1   year     1650 non-null   Int64
 2   export   1650 non-null   int64
dtypes: Int64(1), int64(1), object(1)
memory usage: 40.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  1050 non-null   object
 1   year     1050 non-null   Int64
 2   import   1050 non-null   int64
dtypes: Int64(1), int64(1), object(1)
memory usage: 25.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   country                1050 non-null   object
 1   year                   1050 non-null   Int64
 2   consumption_importers  1050 non-null   int64
dtypes: Int64(1), int64(1), object(1)
memory usage: 25.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1650 entries, 0 to 1649
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   country               1650 non-null   object
 1   coffee_type           1650 non-null   object
 2   year                  1650 non-null   Int64
 3   consumption_domestic  1650 non-null   Int64
dtypes: Int64(2), object(2)
memory usage: 54.9+ KB
None

In [36]:
# remove time element from datetime format from green_prices
green_prices["date"] = pd.to_datetime(green_prices["date"]).dt.floor("D")
# check the green_prices dataframe again after removing time element to ensure date is in the correct format and there are no issues
print(green_prices.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14362 entries, 0 to 14361
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    14362 non-null  datetime64[ns]
 1   value   14362 non-null  float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 224.5 KB
None

In [37]:
green_prices.head()

        date   value
0 1969-06-02  0.3725
1 1969-06-03  0.3725
2 1969-06-04  0.3725
3 1969-06-05  0.3725
4 1969-06-06  0.3725

In [38]:
# Check for missing values in all dataframes again after type conversions to see if any new missing values were introduced due to coercion (e.g. if there were any non-date values in the date column that got converted to NaT, or non-numeric values in production/consumption that got converted to NaN)
print("Missing values in green_prices:", green_prices.isnull().sum())
print("Missing values in production_pivot:", production_pivot.isnull().sum())
print("Missing values in export_pivot:", export_pivot.isnull().sum())
print("Missing values in import_pivot:", import_pivot.isnull().sum())
print("Missing values in consumption_importers_pivot:", consumption_importers_pivot.isnull().sum())
print("Missing values in consumption_domestic_pivot:", consumption_domestic_pivot.isnull().sum())


#

Missing values in green_prices: date     0
value    0
dtype: int64
Missing values in production_pivot: country        0
coffee_type    0
year           0
production     0
dtype: int64
Missing values in export_pivot: country    0
year       0
export     0
dtype: int64
Missing values in import_pivot: country    0
year       0
import     0
dtype: int64
Missing values in consumption_importers_pivot: country                  0
year                     0
consumption_importers    0
dtype: int64
Missing values in consumption_domestic_pivot: country                 0
coffee_type             0
year                    0
consumption_domestic    0
dtype: int64

In [39]:
# check shapes
print("Shape of green_prices:", green_prices.shape)
print("Shape of production_pivot:", production_pivot.shape)
print("Shape of export_pivot:", export_pivot.shape)
print("Shape of import_pivot:", import_pivot.shape)
print("Shape of consumption_importers_pivot:", consumption_importers_pivot.shape)
print("Shape of consumption_domestic_pivot:", consumption_domestic_pivot.shape)

# going to leave the nulls as is for now since we will likely need to handle them differently depending on the analysis (e.g. we may want to fill them with 0 for production/consumption, but not for prices, or we may want to drop rows with missing values for certain analyses but not others)

Shape of green_prices: (14362, 2)
Shape of production_pivot: (1650, 4)
Shape of export_pivot: (1650, 3)
Shape of import_pivot: (1050, 3)
Shape of consumption_importers_pivot: (1050, 3)
Shape of consumption_domestic_pivot: (1650, 4)

In [40]:
# check for duplicates again after all transformations to ensure we don't have any duplicate rows that could skew our analysis
# only have df namea nd number of duplicates
# duplicates based on country, year and coffee type (for production and consumption_domestic) since those are the key dimensions we will be analyzing

dfs = {
    "green coffee prices": green_prices,
    "production": production_pivot,
    "export": export_pivot,
    "import": import_pivot,
    "cons_importers": consumption_importers_pivot,
    "cons_domestic": consumption_domestic_pivot
}

for name, df in dfs.items():
    dup_count = df.duplicated().sum()
    print(f"Duplicates in {name}: {dup_count}")

Duplicates in green coffee prices: 0
Duplicates in production: 0
Duplicates in export: 0
Duplicates in import: 0
Duplicates in cons_importers: 0
Duplicates in cons_domestic: 0

In [41]:
# check for validity and range in numeric columns to identify any potential outliers or data entry errors that may need to be addressed before analysis (e.g. negative production values, extremely high prices, etc.)
for df in [
    green_prices,
    production_pivot,
    export_pivot,
    import_pivot,
    consumption_importers_pivot,
    consumption_domestic_pivot,
]:
    print(df.describe())

                                date         value
count                          14362  14362.000000
mean   1997-11-01 18:50:16.961425920      1.287885
min              1969-06-02 00:00:00      0.350000
25%              1983-08-16 06:00:00      0.800000
50%              1997-10-27 12:00:00      1.230000
75%              2012-01-29 06:00:00      1.550000
max              2026-02-19 00:00:00      4.335600
std                              NaN      0.646945
           year        production
count    1650.0            1650.0
mean     2004.5  136808981.818182
std    8.658066   391130322.34495
min      1990.0               0.0
25%      1997.0         2280000.0
50%      2004.5        21030000.0
75%      2012.0        92640000.0
max      2019.0      3907860000.0
           year        export
count    1650.0  1.650000e+03
mean     2004.5  9.894891e+07
std    8.658066  2.530945e+08
min      1990.0  0.000000e+00
25%      1997.0  1.080000e+06
50%      2004.5  8.730000e+06
75%      2012.0  8.134500e+07
max      2019.0  2.138220e+09
           year        import
count    1050.0  1.050000e+03
mean     2004.5  1.689898e+08
std    8.659566  2.984960e+08
min      1990.0  0.000000e+00
25%      1997.0  1.632000e+07
50%      2004.5  5.397000e+07
75%      2012.0  1.847100e+08
max      2019.0  1.851240e+09
           year  consumption_importers
count    1050.0           1.050000e+03
mean     2004.5           1.250999e+08
std    8.659566           2.348742e+08
min      1990.0           0.000000e+00
25%      1997.0           1.234500e+07
50%      2004.5           4.485000e+07
75%      2012.0           1.160250e+08
max      2019.0           1.638600e+09
           year  consumption_domestic
count    1650.0                1650.0
mean     2004.5       37082887.941212
std    8.658066      133119436.794417
min      1990.0                   0.0
25%      1997.0              240000.0
50%      2004.5             3330000.0
75%      2012.0            19500000.0
max      2019.0          1332000000.0

In [42]:
# there is a negative value in the exports table
# identify the row with the negative export value to investigate further and determine if it is a data entry error that can be corrected or if it should be treated as missing data
negative_exports = export_pivot[export_pivot["export"] < 0]
print("Rows with negative export values:\n", negative_exports)

Rows with negative export values:
 Empty DataFrame
Columns: [country, year, export]
Index: []

In [43]:
# investigate Brazil production vs export data
brazil = production_pivot[production_pivot["country"] == "Brazil"]
exports = export_pivot[export_pivot["country"] == "Brazil"]

merged = brazil.merge(exports, on=["country","year"], suffixes=("_prod","_exp"))

merged[merged["year"].isin([2013,2014,2015,2016,2017,2018,2019,2020])]

   country      coffee_type  year  production      export
23  Brazil  Arabica/Robusta  2013  3281340000  1899060000
24  Brazil  Arabica/Robusta  2014  3198300000           0
25  Brazil  Arabica/Robusta  2015  3172260000           0
26  Brazil  Arabica/Robusta  2016  3407280000  2056140000
27  Brazil  Arabica/Robusta  2017  3164400000  1855500000
28  Brazil  Arabica/Robusta  2018  3907860000  2138220000
29  Brazil  Arabica/Robusta  2019  3492660000           0

In [44]:
# identify what columns in all the dataframes contain the value -2147483648 (which is the minimum value for a 32-bit integer and may indicate an error or placeholder value in the data)
for name, df in dfs.items():
    #print(df["country"].value_counts())
    print("Columns with -2147483648 value:")
    for col in df.columns:
        if (df[col] == -2147483648).any():
            print(f" - {col}")

Columns with -2147483648 value:
Columns with -2147483648 value:
Columns with -2147483648 value:
Columns with -2147483648 value:
Columns with -2147483648 value:
Columns with -2147483648 value:

In [45]:
# looks like only 3 instances of these placeholder values in export - replace with 0
export_pivot["export"] = export_pivot["export"].replace(-2147483648, 0) 

# count after replacement to confirm that the placeholder values have been replaced
print("Count of -2147483648 in export after replacement:", (export_pivot["export"] == -2147483648).sum())

Count of -2147483648 in export after replacement: 0

In [46]:
# check if export is larger than production for each production country-year combination
merged = production_pivot.merge(export_pivot, on=["country","year"], how="left", suffixes=("_prod","_exp"))
merged["% diff"] = (merged["export"] - merged["production"]) / merged["production"] * 100
merged["export_larger_than_production"] = merged["export"] > merged["production"]
export_larger = merged[merged["export_larger_than_production"] == True]
print("Rows where export is larger than production:\n", export_larger[["country","year","production","export","% diff" ]])


# not going to drop these rows since we don't know if they are errors or if there are valid reasons for export being larger than production (e.g. re-exports, stockpiles, etc.) 
# will need to investigate further during analysis and potentially handle on a case-by-case basis depending on the country and year

Rows where export is larger than production:
            country  year  production     export     % diff
0           Angola  1990     3000000    5040000       68.0
1          Bolivia  1990     7380000    9360000  26.829268
3          Burundi  1990    29220000   35100000  20.123203
4          Ecuador  1990    90240000  107040000  18.617021
7           Malawi  1990     6300000    7440000  18.095238
...            ...   ...         ...        ...        ...
1630      Honduras  2019   355860000  405900000   14.06171
1631         India  2019   299280000  361680000   20.85004
1638     Nicaragua  2019   172920000  177240000   2.498265
1641  Sierra Leone  2019     2400000    2820000       17.5
1644          Togo  2019     2460000    3480000  41.463415

[373 rows x 5 columns]

In [47]:
merged["country"].unique()

array(['Angola', 'Bolivia', 'Brazil', 'Burundi', 'Ecuador', 'Indonesia',
       'Madagascar', 'Malawi', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Rwanda', 'TimorLeste', 'Zimbabwe', 'Republic of the Congo',
       'Cuba', 'Dominican Republic', 'Haiti', 'Philippines', 'Tanzania',
       'Zambia', 'Cameroon', 'Central African Republic', 'Colombia',
       'Costa Rica', 'Côte DIvoire', 'Democratic Republic of the Congo',
       'El Salvador', 'Equatorial Guinea', 'Ethiopia', 'Gabon', 'Ghana',
       'Guatemala', 'Guinea', 'Guyana', 'Honduras', 'India', 'Jamaica',
       'Kenya', 'Lao PeopleS Democratic Republic', 'Liberia', 'Mexico',
       'Nepal', 'Nicaragua', 'Nigeria', 'Panama', 'Sierra Leone',
       'Sri Lanka', 'Thailand', 'Togo', 'Trinidad  Tobago', 'Uganda',
       'Venezuela', 'Viet Nam', 'Yemen'], dtype=object)

In [48]:
green_prices.columns

Index(['date', 'value'], dtype='object')

In [49]:
# identify 0 value in green_prices to see if there are any potential data entry errors or if 0 is a valid price (e.g. for certain years or countries)
zero_price_rows = green_prices[green_prices["value"] == 0]
print("Rows with 0 value in green_prices:\n", zero_price_rows)

Rows with 0 value in green_prices:
 Empty DataFrame
Columns: [date, value]
Index: []

In [50]:
# internet search revealed that green coffe was priced at $2.484 on 28-10-2024
# replace 0 with 2.48

green_prices.loc[green_prices["value"] == 0, "value"] = 2.484

# check that the replacement worked via the date
print(green_prices[green_prices["date"] == "2024-10-28"])

# success

            date  value
14018 2024-10-28  2.484

In [51]:
# 0 values in other data tables makes sense
# some do not import, some do not export, some do not produce, etc.

In [ ]:
from sqlalchemy import create_engine, text

DB_USER = "***"
DB_PASS = "***"
DB_HOST = "***"
DB_PORT = "***"
DB_NAME = "coffee_market"

# connect to MySQL server
engine = create_engine(
    f"mysql+pymysql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}"
)

# drop table if exists
# create new table
with engine.connect() as conn:
    conn.execute(text(f"DROP DATABASE IF EXISTS {DB_NAME}"))
    conn.execute(text(f"CREATE DATABASE {DB_NAME}"))
    print(f"Database {DB_NAME} created")

# connect to database
engine = create_engine(
    f"mysql+pymysql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

# dataframes to load as tables into MySQL
tables = {
    "production": production_pivot,
    "export": export_pivot,
    "import": import_pivot,
    "consumption_importers": consumption_importers_pivot,
    "consumption_domestic": consumption_domestic_pivot,
    "prices": green_prices
}

# load in the dataframes
for name, df in tables.items():
    df.to_sql(
        name=name,
        con=engine,
        if_exists="replace",
        index=False,
        method="multi",
        chunksize=1000
    )
    print(f"Loaded {name} ({len(df)} rows)")

print("All tables loaded successfully")

Database coffee_market created
Loaded production (1650 rows)
Loaded export (1650 rows)
Loaded import (1050 rows)
Loaded consumption_importers (1050 rows)
Loaded consumption_domestic (1650 rows)
Loaded prices (14362 rows)
All tables loaded successfully